In [1]:
#importing the libaries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the dataset
dataset=pd.read_csv("CKD.csv")

In [7]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [12]:
indep1=dataset.drop(columns=['classification'])

In [13]:
dep=dataset['classification']

In [14]:
indep = pd.get_dummies(indep1, drop_first=True)

In [15]:
indep

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,True,False,False,False,False,False,False,True,True,False
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,True,False,False,False,False,False,True,False,False
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,True,False,False,False,False,False,True,False,False
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,True,False,False,False,False,False,True,False,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,True,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,True,False,False,False,False,False,True,False,False
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,True,False,False,True,True,False,True,False,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,True,False,False,True,True,False,False,False,False
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,True,False,False,True,True,False,True,False,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,True,False,False,False,False,False,True,False,False

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [18]:
from sklearn.model_selection import GridSearchCV
# Define the parameter grid
param_grid = {'C': [0.01, 0.1, 1, 10, 100], # Regularization strength
    'penalty': ['l1', 'l2', 'elasticnet', 'none'], # Penalty type
    'solver': ['lbfgs', 'liblinear', 'saga'],} # Solvers compatible with penalties}

from sklearn.linear_model import LogisticRegression
grid = GridSearchCV(LogisticRegression(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train, y_train)

Fitting 5 folds for each of 60 candidates, totalling 300 fits

E:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
175 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "E:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1218, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "E:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 64, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver lbfgs supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "E:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1218, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "E:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 64, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver lbfgs supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "E:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1218, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "E:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 72, in _check_solver
    raise ValueError(
        f"Only 'saga' solver supports elasticnet penalty, got solver={solver}."
    )
ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "E:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1228, in fit
    raise ValueError("l1_ratio must be specified when penalty is elasticnet.")
ValueError: l1_ratio must be specified when penalty is elasticnet.

--------------------------------------------------------------------------------
7 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegression must be a str among {'l2', 'elasticnet', 'l1'} or None. Got 'none' instead.

--------------------------------------------------------------------------------
12 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegression must be a str among {'elasticnet', 'l2', 'l1'} or None. Got 'none' instead.

--------------------------------------------------------------------------------
33 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegression must be a str among {'elasticnet', 'l1', 'l2'} or None. Got 'none' instead.

--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegression must be a str among {'l1', 'elasticnet', 'l2'} or None. Got 'none' instead.

--------------------------------------------------------------------------------
9 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegression must be a str among {'l1', 'l2', 'elasticnet'} or None. Got 'none' instead.

--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegression must be a str among {'l2', 'l1', 'elasticnet'} or None. Got 'none' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
E:\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [       nan 0.20194378 0.48429303 0.98496077 0.92971619 0.98496077
        nan        nan        nan        nan        nan        nan
        nan 0.96262951 0.966259   0.98868958 0.95910985 0.98496077
        nan        nan        nan        nan        nan        nan
        nan 0.97751924 0.98500464 0.98876    0.97390477 0.98129068
        nan        nan        nan        nan        nan        nan
        nan 0.98139017 0.97763358 0.98880386 0.98514677 0.97763358
        nan        nan        nan        nan        nan        nan
        nan 0.9626816  0.97763358 0.98135296 0.97775352 0.97763358
        nan        nan        nan        nan        nan        nan]
  warnings.warn(

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10, 100],
                         'penalty': ['l1', 'l2', 'elasticnet', 'none'],
                         'solver': ['lbfgs', 'liblinear', 'saga']},
             scoring='f1_weighted', verbose=3)

In [19]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test)

In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

In [21]:
# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [22]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'C': 10, 'penalty': 'l2', 'solver': 'lbfgs'}: 0.9850141736106648

In [23]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[51  0]
 [ 2 80]]

In [24]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

          no       0.96      1.00      0.98        51
         yes       1.00      0.98      0.99        82

    accuracy                           0.98       133
   macro avg       0.98      0.99      0.98       133
weighted avg       0.99      0.98      0.99       133

In [25]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9997608799617408

In [26]:
table=pd.DataFrame.from_dict(re)

In [27]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_penalty,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003725,0.000983,0.000000,0.000000,0.01,l1,lbfgs,"{'C': 0.01, 'penalty': 'l1', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
1,0.009098,0.001127,0.016742,0.004102,0.01,l1,liblinear,"{'C': 0.01, 'penalty': 'l1', 'solver': 'liblin...",0.200200,0.189203,0.206772,0.206772,0.206772,0.201944,0.006860,25
2,0.013905,0.003679,0.016219,0.003964,0.01,l1,saga,"{'C': 0.01, 'penalty': 'l1', 'solver': 'saga'}",0.486532,0.501410,0.477841,0.477841,0.477841,0.484293,0.009196,24
3,0.041278,0.015749,0.015141,0.000570,0.01,l2,lbfgs,"{'C': 0.01, 'penalty': 'l2', 'solver': 'lbfgs'}",1.000000,0.981014,0.962573,1.000000,0.981217,0.984961,0.014023,6
4,0.008183,0.001618,0.011923,0.002037,0.01,l2,liblinear,"{'C': 0.01, 'penalty': 'l2', 'solver': 'liblin...",0.890759,0.944161,0.888515,0.962573,0.962573,0.929716,0.033416,23
5,0.018871,0.001933,0.017020,0.001363,0.01,l2,saga,"{'C': 0.01, 'penalty': 'l2', 'solver': 'saga'}",1.000000,0.981014,0.962573,1.000000,0.981217,0.984961,0.014023,6
6,0.002058,0.000700,0.000000,0.000000,0.01,elasticnet,lbfgs,"{'C': 0.01, 'penalty': 'elasticnet', 'solver':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
7,0.001874,0.000884,0.000000,0.000000,0.01,elasticnet,liblinear,"{'C': 0.01, 'penalty': 'elasticnet', 'solver':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
8,0.002346,0.000946,0.000000,0.000000,0.01,elasticnet,saga,"{'C': 0.01, 'penalty': 'elasticnet', 'solver':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
9,0.001543,0.000700,0.000000,0.000000,0.01,none,lbfgs,"{'C': 0.01, 'penalty': 'none', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
10,0.001341,0.000287,0.000000,0.000000,0.01,none,liblinear,"{'C': 0.01, 'penalty': 'none', 'solver': 'libl...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
11,0.001946,0.000931,0.000000,0.000000,0.01,none,saga,"{'C': 0.01, 'penalty': 'none', 'solver': 'saga'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
12,0.001954,0.000809,0.000000,0.000000,0.10,l1,lbfgs,"{'C': 0.1, 'penalty': 'l1', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
13,0.006377,0.002441,0.012490,0.003151,0.10,l1,liblinear,"{'C': 0.1, 'penalty': 'l1', 'solver': 'libline...",0.981569,0.962264,0.925524,0.962573,0.981217,0.962630,0.020402,21
14,0.032387,0.004057,0.010260,0.001162,0.10,l1,saga,"{'C': 0.1, 'penalty': 'l1', 'solver': 'saga'}",0.962963,0.981014,0.944023,0.981031,0.962264,0.966259,0.013836,19
15,0.011860,0.002977,0.010708,0.002365,0.10,l2,lbfgs,"{'C': 0.1, 'penalty': 'l2', 'solver': 'lbfgs'}",1.000000,0.981014,0.981217,1.000000,0.981217,0.988690,0.009235,3
16,0.005328,0.001063,0.009321,0.001494,0.10,l2,liblinear,"{'C': 0.1, 'penalty': 'l2', 'solver': 'libline...",0.945100,0.962636,0.944023,0.981217,0.962573,0.959110,0.013690,22
17,0.028592,0.004141,0.009580,0.001049,0.10,l2,saga,"{'C': 0.1, 'penalty': 'l2', 'solver': 'saga'}",1.000000,0.981014,0.962573,1.000000,0.981217,0.984961,0.014023,6
18,0.001447,0.000500,0.000000,0.000000,0.10,elasticnet,lbfgs,"{'C': 0.1, 'penalty': 'elasticnet', 'solver': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
19,0.001973,0.000417,0.000000,0.000000,0.10,elasticnet,liblinear,"{'C': 0.1, 'penalty': 'elasticnet', 'solver': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
20,0.001500,0.000647,0.000000,0.000000,0.10,elasticnet,saga,"{'C': 0.1, 'penalty': 'elasticnet', 'solver': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
21,0.001717,0.000478,0.000000,0.000000,0.10,none,lbfgs,"{'C': 0.1, 'penalty': 'none', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
22,0.001051,0.000382,0.000000,0.000000,0.10,none,liblinear,"{'C': 0.1, 'penalty': 'none', 'solver': 'libli...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
23,0.001398,0.000325,0.000000,0.000000,0.10,none,saga,"{'C': 0.1, 'penalty': 'none', 'solver': 'saga'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
24,0.001871,0.000991,0.000000,0.000000,1.00,l1,lbfgs,"{'C': 1, 'penalty': 'l1', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
25,0.006181,0.001452,0.009345,0.001930,1.00,l1,liblinear,"{'C': 1, 'penalty': 'l1', 'solver': 'liblinear'}",1.000000,0.981233,0.981217,0.962573,0.962573,0.977519,0.013997,17
26,0.038830,0.004828,0.009827,0.001453,1.00,l1,saga,"{'C': 1, 'penalty': 'l1', 'solver': 'saga'}",1.000000,0.981233,0.981217,1.000000,0.962573,0.985005,0.014010,5
27,0.011068,0.001939,0.008023,0.001846,1.00,l2,lbfgs,"{'C': 1, 'penalty': 'l2', 'solver': 'lbfgs'}",0.981569,0.981014,0.981217,1.000000,1.000000,0.988760,0.009179,2
28,0.006038,0.001576,0.008980,0.002271,1.00,l2,liblinear,"{'C': 1, 'penalty': 'l2', 'solver': 'liblinear'}",0.963284,0.981233,0.962573,0.981217,0.981217,0.973905,0.008965,18
29,0.025368,0.004218,0.008158,0.001050,1.00,l2,saga,"{'C': 1, 'penalty': 'l2', 'solver': 'saga'}",0.981569,0.981233,0.981217,0.981217,0.981217,0.981291,0.000139,11
30,0.001783,0.000824,0.000000,0.000000,1.00,elasticnet,lbfgs,"{'C': 1, 'penalty': 'elasticnet', 'solver': 'l...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
31,0.001471,0.000750,0.000000,0.000000,1.00,elasticnet,liblinear,"{'C': 1, 'penalty': 'elasticnet', 'solver': 'l...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
32,0.001514,0.000992,0.000000,0.000000,1.00,elasticnet,saga,"{'C': 1, 'penalty': 'elasticnet', 'solver': 's...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
33,0.001039,0.000196,0.000000,0.000000,1.00,none,lbfgs,"{'C': 1, 'penalty': 'none', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
34,0.001095,0.000152,0.000000,0.000000,1.00,none,liblinear,"{'C': 1, 'penalty': 'none', 'solver': 'libline...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
35,0.001157,0.000125,0.000000,0.000000,1.00,none,saga,"{'C': 1, 'penalty': 'none', 'solver': 'saga'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
36,0.001499,0.000262,0.000000,0.000000,10.00,l1,lbfgs,"{'C': 10, 'penalty': 'l1', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
37,0.006249,0.001390,0.008602,0.002246,10.00,l1,liblinear,"{'C': 10, 'penalty': 'l1', 'solver': 'liblinear'}",0.963284,0.981233,0.981217,0.981217,1.000000,0.981390,0.011613,9
38,0.045440,0.008573,0.009229,0.000820,10.00,l1,saga,"{'C': 10, 'penalty': 'l1', 'solver': 'saga'}",0.963284,0.981233,0.981217,0.981217,0.981217,0.977634,0.007175,13
39,0.013225,0.004142,0.009745,0.001423,10.00,l2,lbfgs,"{'C': 10, 'penalty': 'l2', 'solver': 'lbfgs'}",0.981569,0.981233,0.981217,1.000000,1.000000,0.988804,0.009142,1
40,0.004643,0.000933,0.009468,0.001601,10.00,l2,liblinear,"{'C': 10, 'penalty': 'l2', 'solver': 'liblinear'}",0.963284,0.981233,0.981217,1.000000,1.000000,0.985147,0.013784,4
41,0.040388,0.015053,0.008306,0.002136,10.00,l2,saga,"{'C': 10, 'penalty': 'l2', 'solver': 'saga'}",0.963284,0.981233,0.981217,0.981217,0.981217,0.977634,0.007175,13
42,0.001172,0.000248,0.000000,0.000000,10.00,elasticnet,lbfgs,"{'C': 10, 'penalty': 'elasticnet', 'solver': '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
43,0.001097,0.000296,0.000000,0.000000,10.00,elasticnet,liblinear,"{'C': 10, 'penalty': 'elasticnet', 'solver': '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
44,0.002159,0.000486,0.000000,0.000000,10.00,elasticnet,saga,"{'C': 10, 'penalty': 'elasticnet', 'solver': '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
45,0.001377,0.000262,0.000000,0.000000,10.00,none,lbfgs,"{'C': 10, 'penalty': 'none', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
46,0.001080,0.000433,0.000000,0.000000,10.00,none,liblinear,"{'C': 10, 'penalty': 'none', 'solver': 'liblin...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
47,0.001608,0.000435,0.000000,0.000000,10.00,none,saga,"{'C': 10, 'penalty': 'none', 'solver': 'saga'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
48,0.001531,0.000610,0.000000,0.000000,100.00,l1,lbfgs,"{'C': 100, 'penalty': 'l1', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
49,0.006529,0.002221,0.010340,0.002633,100.00,l1,liblinear,"{'C': 100, 'penalty': 'l1', 'solver': 'libline...",0.963284,0.981233,0.944023,0.943651,0.981217,0.962682,0.016724,20
50,0.048309,0.011351,0.010403,0.001125,100.00,l1,saga,"{'C': 100, 'penalty': 'l1', 'solver': 'saga'}",0.963284,0.981233,0.981217,0.981217,0.981217,0.977634,0.007175,13
51,0.018639,0.003537,0.011122,0.001600,100.00,l2,lbfgs,"{'C': 100, 'penalty': 'l2', 'solver': 'lbfgs'}",0.963284,0.962264,0.981217,1.000000,1.000000,0.981353,0.016651,10
52,0.007172,0.001798,0.010385,0.001898,100.00,l2,liblinear,"{'C': 100, 'penalty': 'l2', 'solver': 'libline...",0.945100,0.981233,0.981217,0.981217,1.000000,0.977754,0.017873,12
53,0.025940,0.003555,0.009160,0.000570,100.00,l2,saga,"{'C': 100, 'penalty': 'l2', 'solver': 'saga'}",0.963284,0.981233,0.981217,0.981217,0.981217,0.977634,0.007175,13
54,0.001273,0.000297,0.000000,0.000000,100.00,elasticnet,lbfgs,"{'C': 100, 'penalty': 'elasticnet', 'solver': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
55,0.001347,0.000312,0.000000,0.000000,100.00,elasticnet,liblinear,"{'C': 100, 'penalty': 'elasticnet', 'solver': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
56,0.001134,0.000222,0.000000,0.000000,100.00,elasticnet,saga,"{'C': 100, 'penalty': 'elasticnet', 'solver': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
57,0.001231,0.000347,0.000000,0.000000,100.00,none,lbfgs,"{'C': 100, 'penalty': 'none', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
58,0.001171,0.000264,0.000000,0.000000,100.00,none,liblinear,"{'C': 100, 'penalty': 'none', 'solver': 'libli...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
59,0.001092,0.000287,0.000000,0.000000,100.00,none,saga,"{'C': 100, 'penalty': 'none', 'solver': 'saga'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26